//
//  MSetUpViewController.swift
//  Moody
//
//  Created by Neha Pant on 26/06/2019.
//  Copyright (c) 2019 Neha Pant. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MSetUpDisplayLogic: class
{
}

class MSetUpViewController: UIViewController, MSetUpDisplayLogic
{
    var interactor: MSetUpBusinessLogic?
    var router: (NSObjectProtocol & MSetUpRoutingLogic & MSetUpDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup()
    {
        let viewController = self
        let interactor = MSetUpInteractor()
        let presenter = MSetUpPresenter()
        let router = MSetUpRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: View lifecycle

    override func viewDidLoad()
    {
        super.viewDidLoad()
    }
    /**
     Set up Action
     */
    @IBAction func setUpAction(_ sender: Any) {
        router?.routeNextScreen()
    }
}
