//
//  MenstalQNAViewController.swift
//  Moody
//
//  Created by Neha Pant on 28/06/2019.
//  Copyright (c) 2019 Neha Pant. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
private let defaultSelectionDays = 27
protocol MenstalQNADisplayLogic: class
{
}

class MenstalQNAViewController: UIViewController, MenstalQNADisplayLogic, UIPickerViewDataSource, UIPickerViewDelegate
{
    @IBOutlet weak var periodDatePickerView: UIPickerView!
    @IBOutlet weak var bottomView: MBottomView!
    var cycleLenghtArray = [String]()
    var interactor: MenstalQNABusinessLogic?
    var router: (NSObjectProtocol & MenstalQNARoutingLogic & MenstalQNADataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = MenstalQNAInteractor()
        let presenter = MenstalQNAPresenter()
        let router = MenstalQNARouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setDateCycleNumOfMonths()
        setUpBottomView()
        bottomView.setRightBtnTitle(title: "DONE")
        //default values:
        if let aboutCycleLenght = MoodyData.shared.aboutCycleLenght  {
            let array:[String] = aboutCycleLenght.components(separatedBy: " ")
            guard let selectedRow = Int(array[0]) else { return}
                periodDatePickerView.selectRow( selectedRow-1, inComponent: 0, animated: false)
        } else {
            MoodyData.shared.aboutCycleLenght = "28 days"
            periodDatePickerView.selectRow(defaultSelectionDays, inComponent: 0, animated: false)
        }
    }
    override func viewDidAppear(_ animated: Bool) {
        super .viewDidAppear(animated)
    }
    fileprivate func setUpBottomView() {
        bottomView.setRightBtnSelectedState()
        bottomView.leftBtnClickedBlock = {[weak self] () -> Void in
            self?.router?.popScreen()
        }
        bottomView.rightBtnClickedBlock = {[weak self] () -> Void in
            self?.router?.routeNextScreen()
        }
    }
    
    fileprivate func setDateCycleNumOfMonths() {
        for i in 1...31 {
            let countStr = String(i)
            cycleLenghtArray.append(countStr+" "+"days")
        }
    }
    
    func numberOfComponents(in pickerView: UIPickerView) -> Int {
        return 1
    }
    
    func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
        return cycleLenghtArray.count
    }
    func pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {
        return cycleLenghtArray[row]
    }
    func pickerView(_ pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) {
        MoodyData.shared.aboutCycleLenght = cycleLenghtArray[row]
    }
    func pickerView(_ pickerView: UIPickerView, attributedTitleForRow row: Int, forComponent component: Int) -> NSAttributedString? {
        let titleData = cycleLenghtArray[row]
        let myTitle = NSAttributedString(string: titleData, attributes: [NSAttributedString.Key.font:UIFont.boldSystemFont(ofSize: 18.0),NSAttributedString.Key.foregroundColor:UIColor.white])
        return myTitle
    }
}
