//
//  MenstalQNAInteractor.swift
//  Moody
//
//  Created by Neha Pant on 28/06/2019.
//  Copyright (c) 2019 Neha Pant. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MenstalQNABusinessLogic
{
}

protocol MenstalQNADataStore
{
  //var name: String { get set }
}

class MenstalQNAInteractor: MenstalQNABusinessLogic, MenstalQNADataStore
{
  var presenter: MenstalQNAPresentationLogic?
  var worker: MenstalQNAWorker?
  //var name: String = ""
  
  // MARK: Do something
  
}
