//
//  MenstalQNARouter.swift
//  Moody
//
//  Created by Neha Pant on 28/06/2019.
//  Copyright (c) 2019 Neha Pant. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MenstalQNARoutingLogic
{
    func routeNextScreen()
    func popScreen()
    
}

protocol MenstalQNADataPassing
{
  var dataStore: MenstalQNADataStore? { get }
}

class MenstalQNARouter: NSObject, MenstalQNARoutingLogic, MenstalQNADataPassing
{
    weak var viewController: MenstalQNAViewController?
    var dataStore: MenstalQNADataStore?
    
    func routeNextScreen() {
        let menstralReportVC = MenstralReportViewController()
        viewController?.navigationController?.pushViewController(menstralReportVC, animated: true)
    }
    func popScreen(){
        viewController?.navigationController?.popViewController(animated: true)
    }
}
