    //
    //  MenstralReportViewController.swift
    //  Moody
    //
    //  Created by Neha Pant on 28/06/2019.
    //  Copyright (c) 2019 Neha Pant. All rights reserved.
    //
    //  This file was generated by the Clean Swift Xcode Templates so
    //  you can apply clean architecture to your iOS and Mac projects,
    //  see http://clean-swift.com
    //

    import UIKit

    protocol MenstralReportDisplayLogic: class
    {
    }

    class MenstralReportViewController: UIViewController, MenstralReportDisplayLogic
    {
      @IBOutlet weak var aboutPeriodLbl: UILabel!
      @IBOutlet weak var aboutContraceptiveLbl: UILabel!
      @IBOutlet weak var aboutlastPeriodLbl: UILabel!
      @IBOutlet weak var aboutCycleLenghtLbl: UILabel!
      @IBOutlet weak var gobackBtn: UIButton!
      
      var interactor: MenstralReportBusinessLogic?
      var router: (NSObjectProtocol & MenstralReportRoutingLogic & MenstralReportDataPassing)?
     
 
      // MARK: Object lifecycle
      
      override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
      {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
      }
      
      required init?(coder aDecoder: NSCoder)
      {
        super.init(coder: aDecoder)
        setup()
      }
      
      // MARK: Setup
      
      private func setup()
      {
        let viewController = self
        let interactor = MenstralReportInteractor()
        let presenter = MenstralReportPresenter()
        let router = MenstralReportRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
      }
      
      
      // MARK: View lifecycle
      
      override func viewDidLoad()
      {
        super.viewDidLoad()
        gobackBtn.layer.borderColor = UIColor.white.cgColor
        aboutPeriodLbl.text =  MoodyData.shared.aboutPeriod
        aboutContraceptiveLbl.text = MoodyData.shared.aboutContraceptive
        aboutlastPeriodLbl.text = MoodyData.shared.aboutlastPeriod
        aboutCycleLenghtLbl.text = MoodyData.shared.aboutCycleLenght
        
      }
      
      @IBAction func goBackAction(_ sender: Any) {
        router?.popScreen()
      }
      @IBAction func startAppAction(_ sender: Any) {
      }
    }
