//
//  MenstralReportRouter.swift
//  Moody
//
//  Created by Neha Pant on 28/06/2019.
//  Copyright (c) 2019 Neha Pant. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MenstralReportRoutingLogic
{
    func popScreen()
    
}

protocol MenstralReportDataPassing
{
  var dataStore: MenstralReportDataStore? { get }
}

class MenstralReportRouter: NSObject, MenstralReportRoutingLogic, MenstralReportDataPassing
{
    weak var viewController: MenstralReportViewController?
    var dataStore: MenstralReportDataStore?
    
    func popScreen() {
        viewController?.navigationController?.popToRootViewController(animated: true)
    }
}
