//
//  MenstralCycleQNARouter.swift
//  Moody
//
//  Created by Neha Pant on 27/06/2019.
//  Copyright (c) 2019 Neha Pant. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MenstralCycleQNARoutingLogic
{
 func routeNextScreen()
    func popScreen()
}

protocol MenstralCycleQNADataPassing
{
  var dataStore: MenstralCycleQNADataStore? { get }
}

class MenstralCycleQNARouter: NSObject, MenstralCycleQNARoutingLogic, MenstralCycleQNADataPassing
{
  weak var viewController: MenstralCycleQNAViewController?
  var dataStore: MenstralCycleQNADataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: MenstralCycleQNAViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: MenstralCycleQNADataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
    func routeNextScreen() {
        let menstralQNAVC = MenstalQNAViewController()
        viewController?.navigationController?.pushViewController(menstralQNAVC, animated: true)
    }
    func popScreen(){
        viewController?.navigationController?.popViewController(animated: true)
    }
}
