//
//  MenstralCycleQNAPresenter.swift
//  Moody
//
//  Created by Neha Pant on 27/06/2019.
//  Copyright (c) 2019 Neha Pant. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MenstralCycleQNAPresentationLogic
{
}

class MenstralCycleQNAPresenter: MenstralCycleQNAPresentationLogic
{
  weak var viewController: MenstralCycleQNADisplayLogic?
  
}
