//
//  MenstralCycleQNAViewController.swift
//  Moody
//
//  Created by Neha Pant on 27/06/2019.
//  Copyright (c) 2019 Neha Pant. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

private let titleStr = "When did your last period (bleed) start?"
private let dateFormat = "dd MMM yyyy"

protocol MenstralCycleQNADisplayLogic: class
{
}

class MenstralCycleQNAViewController: UIViewController, MenstralCycleQNADisplayLogic
{
    @IBOutlet weak var bottomView: MBottomView!
    @IBOutlet weak var cycleDatePickerView: UIDatePicker!
    var interactor: MenstralCycleQNABusinessLogic?
    var router: (NSObjectProtocol & MenstralCycleQNARoutingLogic & MenstralCycleQNADataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    private func setup()
    {
        let viewController = self
        let interactor = MenstralCycleQNAInteractor()
        let presenter = MenstralCycleQNAPresenter()
        let router = MenstralCycleQNARouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    override func viewDidLoad()
    {
        super.viewDidLoad()
        bottomView.setRightBtnSelectedState()
        setBottomView()
        cycleDatePickerView.setValue(UIColor.white, forKeyPath: "textColor")
        setDefaultCycleDate()
    }
    fileprivate func setBottomView() {
        bottomView.leftBtnClickedBlock = {[weak self] () -> Void in
            self?.router?.popScreen()
        }
        bottomView.rightBtnClickedBlock = {[weak self] () -> Void in
            self?.router?.routeNextScreen()
        }
    }
    fileprivate func setDefaultCycleDate() {
        //setting default value
        let date = Date()
        let formatter = DateFormatter()
        formatter.dateFormat = dateFormat
        let result = formatter.string(from: date)
        MoodyData.shared.aboutlastPeriod = result
    }
    @IBAction func datePickerValueChange(_ sender: Any) {
        // Create date formatter
        let dateFormatter: DateFormatter = DateFormatter()
        // Set date format
        dateFormatter.dateFormat = dateFormat
        // Apply date format
        let selectedDate: String = dateFormatter.string(from: (sender as AnyObject).date)
        MoodyData.shared.aboutlastPeriod = selectedDate
    }
    
}

