//
//  PeriodQNAPresenter.swift
//  Moody
//
//  Created by Neha Pant on 26/06/2019.
//  Copyright (c) 2019 Neha Pant. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PeriodQNAPresentationLogic
{
  //func presentSomething(response: PeriodQNA.periodQNADataSource.Response)
}

class PeriodQNAPresenter: PeriodQNAPresentationLogic
{
  weak var viewController: PeriodQNADisplayLogic?
  
  // MARK: Do something
  
//  func presentSomething(response: PeriodQNA.periodQNADataSource.Response)
//  {
//    let viewModel = PeriodQNA.periodQNADataSource.ViewModel(qNAText: <#T##String?#>, isSelected: <#T##Bool#>)
//    viewController?.displaySomething(viewModel: viewModel)
//  }
}
