//
//  PeriodQNARouter.swift
//  Moody
//
//  Created by Neha Pant on 26/06/2019.
//  Copyright (c) 2019 Neha Pant. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PeriodQNARoutingLogic
{
    func routeNextScreen()
    func popScreen()
}

protocol PeriodQNADataPassing
{
  var dataStore: PeriodQNADataStore? { get }
}

class PeriodQNARouter: NSObject, PeriodQNARoutingLogic, PeriodQNADataPassing
{
    weak var viewController: PeriodQNAViewController?
    var dataStore: PeriodQNADataStore?
    
    func routeNextScreen() {
        let contraceptiveQNAScreen = ContraceptiveViewController()
        viewController?.navigationController?.pushViewController(contraceptiveQNAScreen, animated: true)
    }
    func popScreen(){
        viewController?.navigationController?.popViewController(animated: true)
    }
}
