//
//  PeriodQNAInteractor.swift
//  Moody
//
//  Created by Neha Pant on 26/06/2019.
//  Copyright (c) 2019 Neha Pant. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PeriodQNABusinessLogic
{
  func doSomething(request: PeriodQNA.periodQNADataSource.Request)
}

protocol PeriodQNADataStore
{
  //var name: String { get set }
}

class PeriodQNAInteractor: PeriodQNABusinessLogic, PeriodQNADataStore
{
  var presenter: PeriodQNAPresentationLogic?
  var worker: PeriodQNAWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PeriodQNA.periodQNADataSource.Request)
  {
    worker = PeriodQNAWorker()
    worker?.doSomeWork()
    
    //let response = PeriodQNA.periodQNADataSource.Response()
   // presenter?.presentSomething(response: response)
  }
}
