//
//  PeriodQNAModels.swift
//  Moody
//
//  Created by Neha Pant on 26/06/2019.
//  Copyright (c) 2019 Neha Pant. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PeriodQNA
{
  // MARK: Use cases
  
  enum periodQNADataSource
  {
    struct Request
    {
    }
    struct Response
    {
        var viewModel:ViewModel?
    }
    struct ViewModel
    {
        var qna:[QNA]?
    }
  }
    enum MoodyReport
    {
        struct Request
        {
        }
        struct Response
        {
            var moodyReport:MoodyData?
        }
        struct ViewModel
        {
        }
    }
}
