//
//  ContraceptiveViewController.swift
//  Moody
//
//  Created by Neha Pant on 27/06/2019.
//  Copyright (c) 2019 Neha Pant. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

private let CellIdentifier = "CellIdentifier"
private let titleStr = "Are you on contraceptives?"
private let sectionHeaderHeight = 250
private let HeightOfCell:CGFloat = 90.0
private let cancelTitle = "CANCEL"
protocol ContraceptiveDisplayLogic: class
{
}

class ContraceptiveViewController: UIViewController, ContraceptiveDisplayLogic
{
    @IBOutlet weak var qnaTableView: UITableView!
    @IBOutlet weak var bottomView: MBottomView!
    var interactor: ContraceptiveBusinessLogic?
    var router: (NSObjectProtocol & ContraceptiveRoutingLogic & ContraceptiveDataPassing)?
    var contraceptiveQuesArray = ["No", "I am on the combined pill","I get injections", "I have an implant","I have a coil","I’m on the mini pill (progesterone only)","I have a patch","Other"]
    var qNADataSource = Contraceptive.contraceptiveQNA.ViewModel(qna: [])
    var aboutContraceptive:String?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    private func setup()
    {
        let viewController = self
        let interactor = ContraceptiveInteractor()
        let presenter = ContraceptivePresenter()
        let router = ContraceptiveRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    override func viewDidLoad()
    {
        super.viewDidLoad()
        bottomView.setLeftBtnTitle(title: cancelTitle)
        loadCell()
        setUpBottomView()
        addQNA()
    }
    fileprivate func loadCell() {
        let nib = UINib(nibName: "MQNACellTableViewCell", bundle: nil)
        qnaTableView.register(nib, forCellReuseIdentifier: CellIdentifier)
    }
    fileprivate func setUpBottomView() {
        bottomView.leftBtnClickedBlock = {[weak self] () -> Void in
            self?.router?.popScreen()
        }
        bottomView.rightBtnClickedBlock = {[weak self] () -> Void in
            self?.router?.routeNextScreen()
        }
    }
    fileprivate func addQNA() {
        var qnaLocArray = [QNA]()
        for item in contraceptiveQuesArray {
            let qa = QNA()
            qa.isSelected = false
            qa.qnaStr = item
            qnaLocArray.append(qa)
        }
        qNADataSource = Contraceptive.contraceptiveQNA.ViewModel(qna: qnaLocArray)
    }
}
extension ContraceptiveViewController: UITableViewDataSource, UITableViewDelegate {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let tempView:MTopTitleView = MTopTitleView(frame: CGRect(x: 0, y: 0, width: Int(tableView.frame.width), height: sectionHeaderHeight))
        tempView.titleLbl.text = titleStr
        return tempView
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return contraceptiveQuesArray.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: CellIdentifier) as? MQNACellTableViewCell
        cell?.selectionStyle = .none
        cell?.qnaTxt.text = "" //Text For QNA
        
        if let array = qNADataSource.qna {
            cell?.qnaTxt.text = array[indexPath.row].qnaStr
            if array[indexPath.row].isSelected == true {
                cell?.rightIconSelected()
                bottomView.setRightBtnSelectedState()
            }else {
                cell?.rightIconUnSelected()
            }
        }
        
        return cell!
        
    }
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if let array = qNADataSource.qna {
            MoodyData.shared.aboutContraceptive = array[indexPath.row].qnaStr
            if array[indexPath.row].isSelected == true {
            } else {
                //make all item as false
                for (index, _) in array.enumerated() {
                    array[index].isSelected = false
                }
                array[indexPath.row].isSelected = true
            }
        }
        qnaTableView.reloadData()
    }
}
